#!/usr/bin/env python3
"""Bundle src/ui.lua with an app source file into one runnable Lua file.

OpenOS `require` only searches the package path, so shipping multiple modules
in-game is fragile. This concatenates the framework and app into a single file
whose top-level `...` (script arguments) still reach the app.

Usage: python3 build.py
"""

from __future__ import annotations

import pathlib

ROOT = pathlib.Path(__file__).resolve().parent

HEADER = "-- GENERATED by build.py from src/*.lua -- do not edit by hand.\n"


def bundle(app_source: pathlib.Path, output: pathlib.Path) -> None:
    framework = (ROOT / "src" / "ui.lua").read_text()
    app = app_source.read_text()
    text = (
        HEADER
        + "local ui = (function()\n"
        + framework
        + "\nend)()\n\n"
        + "local __main = function(...)\n"
        + app
        + "\nend\n"
        + "return __main(...)\n"
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text)
    print(f"built {output.relative_to(ROOT)} ({len(text)} bytes)")


def main() -> None:
    bundle(ROOT / "src" / "todo.lua", ROOT / "todo.lua")
    bundle(ROOT / "src" / "ui_spec.lua", ROOT / "tests" / "ui_test.lua")


if __name__ == "__main__":
    main()
